# Generated by Django 2.0 on 2024-12-17 07:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=65)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=65)),
                ('fuel_type', models.CharField(choices=[('petrol', 'petrol'), ('cng', 'cng')], default='petrol', max_length=100)),
                ('odo', models.IntegerField(verbose_name='Odometer Reading')),
                ('location', models.CharField(blank=True, max_length=100, null=True, verbose_name='Location of Petrol pump')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
