# Generated by Django 2.0 on 2024-12-17 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fuel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_type', models.CharField(choices=[('bike', 'bike'), ('car', 'car')], max_length=100)),
                ('vehicle_number', models.CharField(max_length=100)),
                ('log', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='fuel.Log')),
            ],
        ),
    ]
